[objects.py]
  [test_object_to_json]
    bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1808709
    expected: FAIL

  [test_object_to_json_exception]
    bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1808709
    expected: FAIL
