[invalid.py]
  [test_params_locator_value_invalid_value[innerText-\]]
    bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1869538
    expected: FAIL

  [test_params_locator_context_value_invalid_context[non_exiting_context\]]
    expected: FAIL

  [test_params_locator_value_invalid_value[context-value4\]]
    expected: FAIL
